name: Istick
favicon: null
layout_spectrum: 0.97932
typography_spectrum: 0.60913
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Profilering som sitter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#101215'
    - '#77797c'
    - '#c0bfc2'
    - '#9d9fa0'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
