name: Istick
favicon: null
layout_spectrum: 0.7275985
typography_spectrum: 0.3315412
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Profilering som sitter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030202'
    - '#FFFFFF'
    - '#FFF20C'
    - '#FF1630'
    - '#ADAAAB'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
