layout_spectrum: 0
typography_spectrum: 0.3315412
color:
  saturation: 0.9127986
  lightness: 0.9296325
  brandStrength: 0.9946237
  brandColors:
    - '#030202'
    - '#FFFFFF'
    - '#FFF20C'
    - '#FF1630'
    - '#ADAAAB'
  rhythmicContrast: 0.918744
name: Istick
